# Generated by Django 3.1.5 on 2021-02-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablee',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tablee',
            name='message',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tablee',
            name='select_time',
            field=models.TimeField(null=True),
        ),
    ]
