# Generated by Django 3.1.5 on 2021-03-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210226_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablee',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tablee',
            name='message',
        ),
        migrations.RemoveField(
            model_name='tablee',
            name='select_time',
        ),
        migrations.AlterField(
            model_name='tablee',
            name='phone',
            field=models.IntegerField(max_length=50),
        ),
    ]
