# Generated by Django 3.1.5 on 2021-03-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210306_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablee',
            name='phone',
            field=models.IntegerField(max_length=100),
        ),
    ]
